services:
  db:
    image: postgres:17.4
    secrets:
      - postgrespassword
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgrespassword
      PGDATA: /var/lib/postgresql/pgdata
    ports:
      - ${POSTGRES_PORT:-5432}
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    image: ${WEB_IMAGE:-ghcr.io/theendisnear/kanban:latest}
    secrets:
      - databaseurl
      - secretkeybase
    healthcheck:
      test: ["CMD", "curl", "localhost:4000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      DATABASE_URL_FILE: /run/secrets/databaseurl
      SECRET_KEY_BASE_FILE: /run/secrets/secretkeybase
      PHX_HOST: "localhost"
    deploy:
      restart_policy: 
        condition: on-failure
        delay: 5s
        window: 120s
        max_attempts: 3
    ports:
      - 4000:4000
    depends_on:
      - db
    command: >
      bash -c "bin/migrate && bin/server"

volumes:
  db_data:

secrets:
  postgrespassword:
    file: ./secrets/.postgrespassword
  databaseurl:
    file: ./secrets/.databaseurl
  secretkeybase:
    file: ./secrets/.secretkeybase
